// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDi2-PGb3NF-Es_2DukRIAo8Ymyipf5xzg',
    appId: '1:770999682073:web:c7fe756d8cdb29482c9688',
    messagingSenderId: '770999682073',
    projectId: 'third-b73d6',
    authDomain: 'third-b73d6.firebaseapp.com',
    storageBucket: 'third-b73d6.firebasestorage.app',
    measurementId: 'G-KMG9LTDY5F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4mp5HxUbOJtuRp5jjuNDz4hhSsrO0QXA',
    appId: '1:770999682073:android:e6b9f7b5ef8a67cd2c9688',
    messagingSenderId: '770999682073',
    projectId: 'third-b73d6',
    storageBucket: 'third-b73d6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8v3uyDqOHJiVikxfQjOJi_9-RxXAhL_g',
    appId: '1:770999682073:ios:90d5f5b8196095232c9688',
    messagingSenderId: '770999682073',
    projectId: 'third-b73d6',
    storageBucket: 'third-b73d6.firebasestorage.app',
    iosBundleId: 'com.example.third',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDi2-PGb3NF-Es_2DukRIAo8Ymyipf5xzg',
    appId: '1:770999682073:web:ce08e94554f467c42c9688',
    messagingSenderId: '770999682073',
    projectId: 'third-b73d6',
    authDomain: 'third-b73d6.firebaseapp.com',
    storageBucket: 'third-b73d6.firebasestorage.app',
    measurementId: 'G-4PB8326VE9',
  );

}